// Sources/TALLMKit/Types/Message.swift
/// A single turn in a conversation sent to a language model.
///
/// Build conversations as an array of `Message` values and pass them to
/// `TALLMKit.chat(_:messages:parameters:)`. Use the static factory methods
/// for the most readable call sites:
///
/// ```swift
/// let messages: [Message] = [
///     .system("You are a helpful assistant."),
///     .user("What is the capital of France?"),
///     .assistant("Paris."),
///     .user("And Germany?"),
/// ]
/// let response = try await sdk.chat(.openAI(.gpt4oMini), messages: messages)
/// ```
public struct Message: Sendable {

    /// The conversational role of the message author.
    public enum Role: String, Sendable {
        /// Instructions that shape the model's behaviour throughout the conversation.
        /// Providers handle system messages differently: OpenAI and Grok pass them
        /// inline; Anthropic extracts them to a top-level `system` field; Gemini
        /// uses `systemInstruction`.
        case system

        /// A message from the human side of the conversation.
        case user

        /// A previous reply generated by the model, used to maintain history.
        case assistant

        /// The result of a tool or function call, sent back to the model after
        /// local execution. Use `Message.toolResult(toolCallId:content:)` to
        /// create these messages.
        case tool
    }

    /// The author's role in the conversation.
    public let role: Role

    /// The text content of this message, or a JSON-encoded tool result for `.tool` messages.
    public let content: String

    /// The provider-specific call ID linking this tool result back to the original
    /// `ToolCall` that requested it. Only present for `.tool` role messages.
    ///
    /// This value comes from `ToolCall.id` returned in `AIResponse.toolCalls`.
    public let toolCallId: String?

    /// Tool calls the assistant is requesting, if any. Only present for `.assistant` messages
    /// that were built from an `AIResponse` containing tool invocations.
    public let toolCalls: [ToolCall]?

    /// Creates a `Message` with the given role, content, and optional tool call ID.
    public init(role: Role, content: String, toolCallId: String? = nil, toolCalls: [ToolCall]? = nil) {
        self.role = role
        self.content = content
        self.toolCallId = toolCallId
        self.toolCalls = toolCalls
    }

    // MARK: - Factories

    /// Creates a system instruction message.
    ///
    /// System messages guide the model's persona, constraints, or output format.
    /// - Parameter content: The instruction text.
    public static func system(_ content: String) -> Message {
        Message(role: .system, content: content)
    }

    /// Creates a user turn message.
    ///
    /// - Parameter content: The human's input text.
    public static func user(_ content: String) -> Message {
        Message(role: .user, content: content)
    }

    /// Creates an assistant turn message for multi-turn history.
    ///
    /// Include previous assistant replies in the message array to maintain
    /// conversation context across calls.
    /// - Parameter content: The model's previous reply text.
    public static func assistant(_ content: String) -> Message {
        Message(role: .assistant, content: content)
    }

    /// Creates an assistant message from a full `AIResponse`, preserving any tool calls.
    ///
    /// Use this overload when replaying a turn where the model invoked tools. Providers
    /// that require the original `tool_calls` array in the message history (e.g. OpenAI)
    /// will encode it correctly when this factory is used.
    ///
    /// ```swift
    /// let first = try await sdk.send("What's the weather?", model: model, parameters: params)
    /// // … execute tools …
    /// let followUp = try await sdk.chat(model, messages: [
    ///     .user("What's the weather?"),
    ///     .assistant(from: first),
    ///     .toolResult(toolCallId: call.id, content: result),
    /// ])
    /// ```
    public static func assistant(from response: AIResponse) -> Message {
        Message(role: .assistant, content: response.text, toolCalls: response.toolCalls)
    }

    /// Creates a tool result message to return after executing a function call.
    ///
    /// After receiving an `AIResponse` with non-nil `toolCalls`, execute each
    /// function locally and create one `toolResult` message per call:
    ///
    /// ```swift
    /// let result = myWeatherService(city: "Paris")
    /// let toolMsg = Message.toolResult(
    ///     toolCallId: response.toolCalls![0].id,
    ///     content: "{\"temperature\": 22}"
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - toolCallId: The `ToolCall.id` from the model's response.
    ///   - content: The JSON-encoded result of the function execution.
    public static func toolResult(toolCallId: String, content: String) -> Message {
        Message(role: .tool, content: content, toolCallId: toolCallId)
    }
}
